set(headers ${headers}
	include/Utils.h
	include/PCH.h
	include/logger.h
	include/Settings.h
	include/Manager.h
	include/Events.h
	include/Hooks.h
	include/MCP.h
	include/Serialization.h
	include/API.h
	include/CPR.h
	include/offsets.h
	include/PayloadHandlerManager.h
	include/PayloadInterpreter.h
	include/payloadManager.h
	include/Plugin.h
	src/payloadHandlers/payloadHandler.h
)
