set(sources ${sources}
	src/payloadHandlers/actorValueHandler.cpp
	src/payloadHandlers/cameraHandler.cpp
	src/payloadHandlers/CPRHandler.cpp
	src/payloadHandlers/globalTimeHandler.cpp
	src/payloadHandlers/graphVariableHandler.cpp
	src/payloadHandlers/particleHandler.cpp
	src/payloadHandlers/PayloadHandler.h
	src/payloadHandlers/setGhostHandler.cpp
	src/payloadHandlers/spellApplyHandler.cpp
	src/payloadHandlers/spellCastHandler.cpp
	src/CPR.cpp
	src/Events.cpp
	src/Hooks.cpp
	src/main.cpp
	src/Manager.cpp
	src/MCP.cpp
	src/PayloadInterpreter.cpp
	src/PayloadManager.cpp
	src/plugin.cpp
	src/Serialization.cpp
	src/Settings.cpp
	src/Utils.cpp
)
